// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: core/pb/recovery.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Recovery_Unmount_FullMethodName = "/Recovery/Unmount"
)

// RecoveryClient is the client API for Recovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecoveryClient interface {
	Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*UnmountResponse, error)
}

type recoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewRecoveryClient(cc grpc.ClientConnInterface) RecoveryClient {
	return &recoveryClient{cc}
}

func (c *recoveryClient) Unmount(ctx context.Context, in *UnmountRequest, opts ...grpc.CallOption) (*UnmountResponse, error) {
	out := new(UnmountResponse)
	err := c.cc.Invoke(ctx, Recovery_Unmount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecoveryServer is the server API for Recovery service.
// All implementations must embed UnimplementedRecoveryServer
// for forward compatibility
type RecoveryServer interface {
	Unmount(context.Context, *UnmountRequest) (*UnmountResponse, error)
	mustEmbedUnimplementedRecoveryServer()
}

// UnimplementedRecoveryServer must be embedded to have forward compatible implementations.
type UnimplementedRecoveryServer struct {
}

func (UnimplementedRecoveryServer) Unmount(context.Context, *UnmountRequest) (*UnmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unmount not implemented")
}
func (UnimplementedRecoveryServer) mustEmbedUnimplementedRecoveryServer() {}

// UnsafeRecoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecoveryServer will
// result in compilation errors.
type UnsafeRecoveryServer interface {
	mustEmbedUnimplementedRecoveryServer()
}

func RegisterRecoveryServer(s grpc.ServiceRegistrar, srv RecoveryServer) {
	s.RegisterService(&Recovery_ServiceDesc, srv)
}

func _Recovery_Unmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoveryServer).Unmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Recovery_Unmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoveryServer).Unmount(ctx, req.(*UnmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Recovery_ServiceDesc is the grpc.ServiceDesc for Recovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Recovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Recovery",
	HandlerType: (*RecoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unmount",
			Handler:    _Recovery_Unmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/pb/recovery.proto",
}
