name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.25

    - name: Cache s3proxy
      uses: actions/cache@v4
      with:
        path: s3proxy.jar
        key: s3proxy-1.8.0

    - name: Cache xfstests
      uses: actions/cache@v4
      with:
        path: xfstests
        key: xfstests-${{ runner.os }}-v1
        restore-keys: |
          xfstests-${{ runner.os }}-

    - name: Build linux amd64
      run: env CGO_ENABLED=0 go build -o geesefs-linux-amd64 -v && ln -s geesefs-linux-amd64 geesefs

    - name: Run tests
      run: SAME_PROCESS_MOUNT=1 make run-test
      timeout-minutes: 12

    - name: Run xfstests
      run: make run-xfstests
      timeout-minutes: 10

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache-dependency-path: go.sum

    - name: Check formatting
      run: test -z "$(gofmt -l .)"

    - name: Run go vet
      run: go vet ./...
